version: "3"

services:
  postgres:
    container_name: postgres_db
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 6000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5

  django_service:
    container_name: django_service
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - SERVICE_PORT=8081
    depends_on:
      - postgres
    networks:
      - postgres

  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx_task/www:/etc/service/web
    ports:
      - 8888:8080
    environment:
      - SERVICE_HOST=django_service
      - SERVICE_PORT=8081
    depends_on:
      - django_service
    networks:
      - postgres

volumes:
  pgdata:


networks:
  postgres:
    driver: bridge